services:
  web:
    env_file: ./env/.env
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    volumes:
      - .:/code
    depends_on:
      - pgdb
    ports:
      - 8020:8000
    entrypoint: sh /code/entrypoint.sh
    networks:
      - nepse_no_topi
      - external-services

  pgdb:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5452:5432
    env_file: ./env/.env
    command: >
      postgres
        -c wal_level=logical
        -c max_wal_senders=10
        -c max_replication_slots=10
    healthcheck:
      test: [ 'CMD', 'psql', '-U', 'postgres', '-c', 'SELECT 1' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nepse_no_topi

  redis:
    image: redis:alpine
    restart: always
    entrypoint: redis-server --appendonly yes
    # ports:
    #   - 6379:6379
    volumes:
      - ./redis_data:/data
      - ./redis/rc.local:/etc/rc.local
    networks:
      - nepse_no_topi

  worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    entrypoint: [
        "celery", "--app", "nepsenotopi.celery:app", "worker",
        "--loglevel=info", "-Q", "default,realtime"
      ]
    depends_on:
      - web
      - redis
    volumes:
      - .:/code
      - ./logs/:/logs/
    env_file: ./env/.env
    networks:
      - nepse_no_topi
      - external-services

  beat:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    entrypoint: [
        "celery", "--app", "nepsenotopi.celery:app", "beat",
        "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"
      ]
    depends_on:
      - web
      - redis
      - worker
    volumes:
      - .:/code
      - ./logs/:/logs/
    env_file: ./env/.env
    networks:
      - nepse_no_topi

networks:
  nepse_no_topi:
    name: nepse_no_topi
    driver: bridge
  external-services:
    external: true
