# Generated by Django 5.2.3 on 2025-07-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('sector_description', models.CharField(blank=True, choices=[('Commercial Banks', 'Commercial Banks'), ('Manufacturing And Processing', 'Manufacturing And Processing'), ('Hotels And Tourism', 'Hotels And Tourism'), ('Others', 'Others'), ('Hydro Power', 'Hydro Power'), ('Tradings', 'Tradings'), ('Non Life Insurance', 'Non Life Insurance'), ('Development Banks', 'Development Banks'), ('Finance', 'Finance'), ('Microfinance', 'Microfinance'), ('Life Insurance', 'Life Insurance'), ('Investment', 'Investment')], max_length=128, null=True, unique=True)),
                ('active_status', models.CharField(blank=True, choices=[('A', 'Active'), ('S', 'Suspended'), ('D', 'Delisted')], max_length=8, null=True)),
                ('regulatory_body', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sector_description', 'active_status'], name='sector_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('security_name', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('active_status', models.CharField(blank=True, choices=[('A', 'Active'), ('S', 'Suspended'), ('D', 'Delisted')], max_length=8, null=True)),
                ('is_promoter', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'active_status'], name='security_symbol_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShareGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, choices=[('A', 'A'), ('Z', 'Z'), ('B', 'B'), ('G', 'G')], max_length=16, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('capital_range_min', models.IntegerField(blank=True, null=True)),
                ('is_default', models.CharField(blank=True, max_length=16, null=True)),
                ('active_status', models.CharField(blank=True, choices=[('A', 'Active'), ('S', 'Suspended'), ('D', 'Delisted')], max_length=8, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'active_status'], name='share_group_name_idx')],
            },
        ),
    ]
