# Generated by Django 5.2.3 on 2025-07-02 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=128, null=True)),
                ('active_status', models.CharField(blank=True, choices=[('A', 'Active'), ('S', 'Suspended'), ('D', 'Delisted')], max_length=8, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=128, null=True)),
                ('website', models.URLField(blank=True, max_length=256, null=True)),
                ('regulatory_body', models.CharField(blank=True, max_length=128, null=True)),
                ('instrument_type', models.CharField(blank=True, max_length=64, null=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies', to='nepse.sector')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies', to='nepse.security')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('business_date', models.DateTimeField(blank=True, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('total_traded_quantity', models.IntegerField(blank=True, null=True)),
                ('total_traded_value', models.DecimalField(blank=True, decimal_places=4, max_digits=32, null=True)),
                ('previous_day_close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('fifty_two_week_high', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('fifty_two_week_low', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('last_updated_time', models.DateTimeField(blank=True, null=True)),
                ('last_updated_price', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('total_trades', models.IntegerField(blank=True, null=True)),
                ('average_traded_price', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('market_capitalization', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_logs', to='nepse.security')),
            ],
            options={
                'indexes': [models.Index(fields=['business_date', 'security'], name='security_log_idx')],
            },
        ),
    ]
