# Generated by Django 5.2.3 on 2025-07-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepse', '0002_company_securitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='regulatory_body',
        ),
        migrations.AddField(
            model_name='company',
            name='symbol',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='security',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company', to='nepse.security'),
        ),
        migrations.AlterField(
            model_name='security',
            name='is_promoter',
            field=models.CharField(blank=True, choices=[('Y', 'true'), ('N', 'false')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='sharegroup',
            name='is_default',
            field=models.CharField(blank=True, choices=[('Y', 'true'), ('N', 'false')], max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(blank=True, choices=[('EQ', 'Equity'), ('MF', 'Mutual Funds'), ('NCD', 'Non-Convertible Debentures'), ('PS', 'Preference Shares')], max_length=8, null=True, unique=True)),
                ('description', models.CharField(blank=True, choices=[('Equity', 'Equity'), ('Mutual Funds', 'Mutual Funds'), ('Non-Convertible Debentures', 'Non-Convertible Debentures'), ('Preference Shares', 'Preference Shares')], max_length=64, null=True, unique=True)),
                ('active_status', models.CharField(blank=True, choices=[('A', 'Active'), ('S', 'Suspended'), ('D', 'Delisted')], max_length=8, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code', 'active_status'], name='instrument_type_code_idx')],
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='instrument_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies', to='nepse.instrumenttype'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['symbol', 'active_status'], name='company_symbol_idx'),
        ),
    ]
