# Generated by Django 5.2.3 on 2025-07-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepse', '0003_remove_company_regulatory_body_company_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='active_status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive'), ('S', 'Suspended'), ('D', 'Delisted')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='instrument_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='nepse.instrumenttype'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='nepse.sector'),
        ),
        migrations.AlterField(
            model_name='company',
            name='security',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='nepse.security'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='active_status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive'), ('S', 'Suspended'), ('D', 'Delisted')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='active_status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive'), ('S', 'Suspended'), ('D', 'Delisted')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='active_status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive'), ('S', 'Suspended'), ('D', 'Delisted')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to='nepse.security'),
        ),
        migrations.AlterField(
            model_name='sharegroup',
            name='active_status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive'), ('S', 'Suspended'), ('D', 'Delisted')], max_length=8, null=True),
        ),
    ]
