# Generated by Codex on 2026-05-06

import django.db.models.deletion
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nepse', '0004_alter_company_active_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('wacc', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, blank=True, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_shares', to='nepse.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolioshare',
            index=models.Index(fields=['user', 'security'], name='portfolio_user_sec_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolioshare',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='portfolio_quantity_gte_1'),
        ),
    ]
