# Generated by Codex on 2026-05-07

import django.db.models.deletion
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import decimal


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('nepse', '0004_alter_company_active_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))])),
                ('alert_type', models.CharField(choices=[('above', 'Above or equal'), ('below', 'Below or equal')], default='above', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_price', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, blank=True, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='nepse.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'security'], name='watchlist_user_sec_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['is_active', 'is_triggered'], name='watchlist_alert_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.CheckConstraint(condition=models.Q(('target_price__gte', decimal.Decimal('0.01'))), name='watchlist_target_price_gte_001'),
        ),
    ]
