# Generated by Codex on 2026-05-07

import decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioshare',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4),
        ),
        migrations.AlterField(
            model_name='portfolioshare',
            name='share_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='portfolioshare',
            constraint=models.CheckConstraint(condition=models.Q(('share_value__gte', decimal.Decimal('0.01'))), name='portfolio_share_value_gte_001'),
        ),
    ]
